###
POST http://localhost:8080/register-account-declarative
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "personAddress": {
    "street": "Super",
    "city": "Warsaw"
  },
  "email": "jan.kowalski@email.com",
  "phoneNumber": "123123123",
  "personType": "STUDENT"
}


###
POST http://localhost:8080/register-account-programmatic
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "personAddress": {
    "street": "Super",
    "city": "Warsaw"
  },
  "email": "jan.kowalski2@email.com",
  "phoneNumber": "123123123",
  "personType": "STUDENT"
}
